Repository jdxsmith/rancid-tomatillos, pull requests merged in 2020-12, with the labels that each got.

#2 Feature/display movies
  .eslintcache
  public/index.html
  src/App.css
  src/App.js
  src/Movies.css
  src/Movies.js
  src/Poster.css
  src/Poster.js
  src/movieData.js
Labels: enhancement, styling

#4 Update .gitignore file with .eslintcache
  .gitignore
Labels: bug

#7 Feature/displaying an individual movie
  .eslintcache
  package-lock.json
  src/App.css
  src/App.js
  src/Movies.css
  src/Movies.js
  src/Poster.js
Labels: enhancement, styling

#10 Testing/create first tests
  .eslintcache
  src/App.test.js
  src/Movies.test.js
  src/Poster.test.js
Labels: test

#13 Refactor/api call
  .eslintcache
  src/App.js
  src/App.test.js
  src/Movies.js
  src/Movies.test.js
  src/apiCalls.js
Labels: Refactor, test

#15 Styling/update main page
  .eslintcache
  src/App.css
  src/App.js
  src/Movies.js
  src/Poster.css
  src/Poster.js
Labels: Refactor, styling

#17 Add integration test for the Go Back button
  .eslintcache
  src/App.test.js
Labels: test

#20 Refactor/add router to render components
  .eslintcache
  package-lock.json
  package.json
  src/.App.js.swp
  src/App.js
  src/Movies.js
  src/Poster.css
  src/Poster.js
  src/apiCalls.js
  src/index.js
Labels: Refactor, enhancement, styling

#24 Testing/add asynchronous tests
  .eslintcache
  package-lock.json
  src/.App.js.swp
  src/App.js
  src/App.test.js
  src/Movies.css
  src/Movies.js
  src/Movies.test.js
  src/Poster.css
  src/Poster.js
  src/Poster.test.js
  src/apiCalls.js
Labels: Refactor, enhancement, test

#27 Feature/filter movies by genre
  .eslintcache
  src/App.js
  src/Movie-form.css
  src/Movie-form.js
  src/Poster.css
  src/Poster.js
Labels: enhancement, styling

#33 Clean up files to be readable, and remove trailing coma for genre list.
  .eslintcache
  src/App.js
  src/App.test.js
  src/Movie-form.js
  src/Movie-form.test.js
  src/Movies.js
  src/Poster.css
  src/Poster.js
  src/index.js
Labels: Refactor
